const mongoose = require("mongoose");
const razorpaySchema = new mongoose.Schema(
  {
    // Link transaction to your user collection
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // The unique order ID generated by Razorpay backend API
    razorpayOrderId: {
      type: String,
      required: true,
      unique: true,
    },
    // Received from frontend checkout/webhook after a successful payment
    razorpayPaymentId: {
      type: String,
      default: null,
    },
    // Token used to verify authenticity on your backend
    razorpaySignature: {
      type: String,
      default: null,
    },
    // Amount in INR (or your currency) stored as a float/number
    amount: {
      type: Number,
      required: true,
    },
    // Currency code (e.g., 'INR', 'USD')
    currency: {
      type: String,
      required: true,
      default: "INR",
    },
    // Tracks the current life cycle of the payment
    status: {
      type: String,
      required: true,
      enum: ["created", "authorized", "captured", "refunded", "failed"],
      default: "created",
    },
    // Captures payment failure reasons if applicable
    failureReason: {
      type: String,
      default: null,
    },
    // Optional field to track metadata or custom notes sent to Razorpay
    notes: {
      type: Map,
      of: String,
    },
  },
  {
    timestamps: true, // Automatically manages createdAt and updatedAt
  }
);
module.exports = mongoose.model("Payment", razorpaySchema);
